theme: jekyll-theme-minimal
title: "COMPASS"
description: "User documentation for the COMPASS student lab at the University of Wuppertal. The COMPASS lab is located in D.11.01, meaning Building D. Floor 11. Room 1."
show_downloads: false
markdown: kramdown
